version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - aws --version
      - python3 --version  
      - pip3 --version
  build:
    commands:
      - echo Build started on `date`
      - sudo yum update -y
      - sudo yum upgrade -y
      - echo add and Persist PATH of cfn-lint to in ~/.bashrc
      - echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc          
      - echo Apply the changes
      - source ~/.bashrc
      - echo installing cfn-lint
      - pip3 install cfn-lint
      - echo validate cfn template 
      - cfn-lint Requestor.yaml
      - echo package the cfn template
      - aws cloudformation package --template-file Requestor.yaml --s3-bucket mynewestfirstbucket --output-template-file Requestor-artifacts.yaml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - Requestor.yaml
    - Requestor-artifacts.yaml